networks:
  rag-network:
    driver: bridge

services:
  server:
    build:
      context: .
      dockerfile: docker-files/Dockerfile.server
    ports:
      - "127.0.0.1:9000:8000"
    networks:
      - rag-network
    hostname: rag-server
    environment:
      - TOKENIZERS_PARALLELISM=false
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./capec-dataset:/app/capec-dataset
      - ./.env:/app/.env

  client:
    build:
      context: .
      dockerfile: docker-files/Dockerfile.client
    networks:
      - rag-network
    ports:
      - "127.0.0.1:7890:7860"
    environment:
      - SERVER_HOST=rag-server
      - SERVER_PORT=8000
    volumes:
      - ./src:/app/src
      - ./client.py:/app/client.py
      - ./client-requirements.txt:/app/client-requirements.txt

  qdrant:
    image: qdrant/qdrant:v0.10.1
    ports:
      - "127.0.0.1:6343:6333"
      - "127.0.0.1:6344:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - rag-network
    hostname: qdrant

volumes:
  qdrant_storage:
    driver: local
