# Use a Python 3.9 slim image as the base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies in cached mode
COPY client-requirements.txt .

# Update pip and install dependencies
RUN pip install --upgrade pip && \
    pip install -r client-requirements.txt

# Copy only the required files for the application
COPY client.py .
COPY src/ ./src/

# Run the application
CMD ["python", "client.py"]
