FROM python:3.9-slim

WORKDIR /app

# Copy the requirements file and install dependencies in cached mode
COPY requirements.txt .

# Update pip and install dependencies
RUN pip install --upgrade pip && \
    pip install --default-timeout=5000 -r requirements.txt

COPY server.py .

# Expose the port on which the FastAPI app will run
EXPOSE 9000

# Command to run the FastAPI app using uvicorn
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "9000", "--reload"]